package main

func stableContractSpecs(modulePath string) []stableContractSpec {
	rawPath := modulePath + "/eebusraw"
	evidencePath := modulePath + "/eebusevidence"
	field := func(name, typeName, jsonTag string) manifestStableField {
		return manifestStableField{Name: name, Type: typeName, JSONTag: jsonTag}
	}
	stableType := func(name, underlying string, fields ...manifestStableField) manifestStableType {
		if underlying == "struct" && fields == nil {
			fields = []manifestStableField{}
		}
		return manifestStableType{Name: name, Underlying: underlying, Fields: fields}
	}
	enumValue := func(name, value string) manifestStableEnumValue {
		return manifestStableEnumValue{Name: name, Value: value}
	}
	return []stableContractSpec{
		stableSnapshotV1ContractSpec(modulePath, rawPath, evidencePath, field, stableType, enumValue),
		stableNativeSnapshotV2ContractSpec(modulePath, rawPath, evidencePath, field, stableType, enumValue),
		stableIdentityDocumentV1ContractSpec(modulePath, rawPath, evidencePath, field, stableType, enumValue),
		stableReadAuthorizationV1ContractSpec(modulePath, rawPath, evidencePath, field, stableType, enumValue),
		stableEnvelopeV1ContractSpec(modulePath, rawPath, evidencePath, field, stableType, enumValue),
	}
}

type stableContractFieldFactory func(string, string, string) manifestStableField
type stableContractTypeFactory func(string, string, ...manifestStableField) manifestStableType
type stableContractEnumFactory func(string, string) manifestStableEnumValue

func stableSnapshotV1ContractSpec(modulePath, rawPath, evidencePath string, field stableContractFieldFactory, stableType stableContractTypeFactory, enumValue stableContractEnumFactory) stableContractSpec {
	return stableContractSpec{
		importPath: modulePath,
		root:       "SnapshotV1",
		types: []manifestStableType{
			stableType("ObservedRuntimeStateV1", "string"),
			stableType("DegradationReasonV1", "string"),
			stableType("ServiceKindV1", "string"),
			stableType("ObservedSessionStateV1", "string"),
			stableType("FeatureRoleV1", "string"),
			stableType("SnapshotV1", "struct",
				field("Meta", "SnapshotMetaV1", `json:"meta"`),
				field("Status", "RuntimeObservationV1", `json:"status"`),
				field("Pairing", "[]PairingObservationV1", `json:"pairing"`),
				field("Services", "[]ServiceV1", `json:"services"`),
				field("Sessions", "[]SessionV1", `json:"sessions"`),
				field("Devices", "[]DeviceV1", `json:"devices"`),
				field("Entities", "[]EntityV1", `json:"entities"`),
				field("Features", "[]FeatureV1", `json:"features"`),
				field("UseCases", "[]UseCaseV1", `json:"usecases"`),
				field("Opaque", "[]OpaqueObservationV1", `json:"opaque"`),
			),
			stableType("SnapshotMetaV1", "struct",
				field("Contract", "string", `json:"contract"`),
				field("Runtime", rawPath+".RedactedID", `json:"runtime"`),
				field("LocalSKI", "string", `json:"local_ski"`),
				field("MaskTier", rawPath+".MaskTier", `json:"mask_tier"`),
				field("CapturedAt", "time.Time", `json:"captured_at"`),
				field("DataTimestamp", "time.Time", `json:"data_timestamp"`),
				field("DataHash", "string", `json:"data_hash,omitempty"`),
			),
			stableType("RuntimeObservationV1", "struct",
				field("State", "ObservedRuntimeStateV1", `json:"state"`),
				field("Degradation", "*DegradationV1", `json:"degradation,omitempty"`),
			),
			stableType("DegradationV1", "struct",
				field("Reason", "DegradationReasonV1", `json:"reason"`),
				field("Since", "time.Time", `json:"since"`),
			),
			stableType("PairingObservationV1", "struct",
				field("RemoteSKI", "string", `json:"remote_ski"`),
				field("State", rawPath+".PairingState", `json:"state"`),
				field("Since", "time.Time", `json:"since"`),
				field("Opaque", "*[]OpaqueObservationV1", `json:"opaque,omitempty"`),
			),
			stableType("ServiceV1", "struct",
				field("SKI", "string", `json:"ski"`),
				field("SHIPID", "*string", `json:"ship_id,omitempty"`),
				field("Kind", "ServiceKindV1", `json:"kind"`),
				field("Visible", "bool", `json:"visible"`),
				field("Paired", "bool", `json:"paired"`),
				field("Name", "*string", `json:"name,omitempty"`),
				field("Identifier", "*string", `json:"identifier,omitempty"`),
				field("Brand", "*string", `json:"brand,omitempty"`),
				field("Type", "*string", `json:"type,omitempty"`),
				field("Model", "*string", `json:"model,omitempty"`),
				field("SecondaryDigest", "*string", `json:"secondary_digest,omitempty"`),
				field("Opaque", "*[]OpaqueObservationV1", `json:"opaque,omitempty"`),
			),
			stableType("SessionV1", "struct",
				field("ID", "string", `json:"id"`),
				field("RemoteSKI", "string", `json:"remote_ski"`),
				field("State", "ObservedSessionStateV1", `json:"state"`),
				field("Since", "time.Time", `json:"since"`),
				field("Opaque", "*[]OpaqueObservationV1", `json:"opaque,omitempty"`),
			),
			stableType("DeviceV1", "struct",
				field("SKI", "string", `json:"ski"`),
				field("SHIPID", "*string", `json:"ship_id,omitempty"`),
				field("Address", "string", `json:"address"`),
				field("Type", "string", `json:"type"`),
				field("Description", "*string", `json:"description,omitempty"`),
				field("Metadata", "*MetadataV1", `json:"metadata,omitempty"`),
				field("SecondaryDigest", "*string", `json:"secondary_digest,omitempty"`),
				field("Opaque", "*[]OpaqueObservationV1", `json:"opaque,omitempty"`),
			),
			stableType("EntityV1", "struct",
				field("DeviceAddress", "string", `json:"device_address"`),
				field("EntityAddress", "string", `json:"entity_address"`),
				field("Type", "string", `json:"type"`),
				field("Description", "*string", `json:"description,omitempty"`),
				field("SecondaryDigest", "*string", `json:"secondary_digest,omitempty"`),
				field("Opaque", "*[]OpaqueObservationV1", `json:"opaque,omitempty"`),
			),
			stableType("FeatureV1", "struct",
				field("DeviceAddress", "string", `json:"device_address"`),
				field("EntityAddress", "string", `json:"entity_address"`),
				field("FeatureAddress", "string", `json:"feature_address"`),
				field("Type", "string", `json:"type"`),
				field("Role", "string", `json:"role"`),
				field("Description", "*string", `json:"description,omitempty"`),
				field("SecondaryDigest", "*string", `json:"secondary_digest,omitempty"`),
				field("Opaque", "*[]OpaqueObservationV1", `json:"opaque,omitempty"`),
			),
			stableType("UseCaseV1", "struct",
				field("ContextAddress", "string", `json:"context_address"`),
				field("Name", "string", `json:"name"`),
				field("Actor", "string", `json:"actor"`),
				field("ResolvedRole", "*string", `json:"resolved_role,omitempty"`),
				field("Scenarios", "*[]string", `json:"scenarios,omitempty"`),
				field("Version", "*string", `json:"version,omitempty"`),
				field("Availability", "*bool", `json:"availability,omitempty"`),
				field("DocumentSubrevision", "*string", `json:"document_subrevision,omitempty"`),
				field("SecondaryDigest", "*string", `json:"secondary_digest,omitempty"`),
				field("Opaque", "*[]OpaqueObservationV1", `json:"opaque,omitempty"`),
			),
			stableType("OpaqueObservationV1", "struct",
				field("Path", "string", `json:"path"`),
				field("Source", "string", `json:"source"`),
				field("Value", "OpaqueValueV1", `json:"value"`),
			),
			stableType("OpaqueValueV1", "struct",
				field("Scalar", "*OpaqueScalarV1", `json:"scalar,omitempty"`),
				field("Array", "*[]OpaqueValueV1", `json:"array,omitempty"`),
				field("Object", "*map[string]OpaqueValueV1", `json:"object,omitempty"`),
			),
			stableType("OpaqueScalarV1", "struct",
				field("Null", "*bool", `json:"null,omitempty"`),
				field("Boolean", "*bool", `json:"boolean,omitempty"`),
				field("Integer", "*int64", `json:"integer,omitempty"`),
				field("String", "*string", `json:"string,omitempty"`),
			),
			stableType("MetadataV1", "struct",
				field("Values", "map[string]MetadataValueV1", `json:"values"`),
			),
			stableType("MetadataValueV1", "struct",
				field("Null", "*bool", `json:"null,omitempty"`),
				field("Boolean", "*bool", `json:"boolean,omitempty"`),
				field("Integer", "*int64", `json:"integer,omitempty"`),
				field("String", "*string", `json:"string,omitempty"`),
			),
			stableType("RedactedSnapshotV1", "struct",
				field("Meta", "RedactedSnapshotMetaV1", `json:"meta"`),
				field("Status", "RuntimeObservationV1", `json:"status"`),
				field("Pairing", "[]"+rawPath+".PairingState", `json:"pairing"`),
				field("Services", "[]RedactedServiceV1", `json:"services"`),
				field("Sessions", "[]RedactedSessionV1", `json:"sessions"`),
				field("Devices", "[]RedactedDeviceV1", `json:"devices"`),
				field("Entities", "[]RedactedEntityV1", `json:"entities"`),
				field("Features", "[]RedactedFeatureV1", `json:"features"`),
				field("UseCases", "[]RedactedUseCaseV1", `json:"usecases"`),
			),
			stableType("RedactedSnapshotMetaV1", "struct",
				field("Contract", "string", `json:"contract"`),
				field("Runtime", rawPath+".RedactedID", `json:"runtime"`),
				field("LocalSKI", rawPath+".RedactedID", `json:"local_ski"`),
				field("MaskTier", rawPath+".MaskTier", `json:"mask_tier"`),
				field("CapturedAt", "time.Time", `json:"captured_at"`),
				field("DataTimestamp", "time.Time", `json:"data_timestamp"`),
				field("DataHash", "string", `json:"data_hash,omitempty"`),
			),
			stableType("RedactedServiceV1", "struct",
				field("ID", rawPath+".RedactedID", `json:"id"`),
				field("Kind", "ServiceKindV1", `json:"kind"`),
				field("Visible", "bool", `json:"visible"`),
				field("Paired", "bool", `json:"paired"`),
			),
			stableType("RedactedSessionV1", "struct",
				field("ID", rawPath+".RedactedID", `json:"id"`),
				field("Remote", rawPath+".RedactedID", `json:"remote"`),
				field("State", "ObservedSessionStateV1", `json:"state"`),
				field("Since", "time.Time", `json:"since"`),
			),
			stableType("RedactedDeviceV1", "struct",
				field("ID", rawPath+".RedactedID", `json:"id"`),
				field("Entities", "[]RedactedEntityV1", `json:"entities"`),
				field("UseCaseClaims", "[]RedactedUseCaseV1", `json:"usecase_claims"`),
			),
			stableType("RedactedEntityV1", "struct",
				field("ID", rawPath+".RedactedID", `json:"id"`),
				field("Features", "[]RedactedFeatureV1", `json:"features"`),
			),
			stableType("RedactedFeatureV1", "struct",
				field("ID", rawPath+".RedactedID", `json:"id"`),
				field("Role", "FeatureRoleV1", `json:"role"`),
			),
			stableType("RedactedUseCaseV1", "struct",
				field("ID", rawPath+".RedactedID", `json:"id"`),
			),
		},
		enums: []stableEnumSpec{
			{additional: []string{"NativeSnapshotContractV2"}, exact: true, values: []manifestStableEnumValue{
				enumValue("SnapshotContractV1", "helianthus.eebus.runtime.raw-snapshot.v1"),
			}},
			{exact: true, typeName: "ObservedRuntimeStateV1", values: []manifestStableEnumValue{
				enumValue("ObservedRuntimeStateV1Unknown", "unknown"),
				enumValue("ObservedRuntimeStateV1Stopped", "stopped"),
				enumValue("ObservedRuntimeStateV1Starting", "starting"),
				enumValue("ObservedRuntimeStateV1Ready", "ready"),
				enumValue("ObservedRuntimeStateV1Degraded", "degraded"),
				enumValue("ObservedRuntimeStateV1Shutdown", "shutdown"),
			}},
			{exact: true, typeName: "DegradationReasonV1", values: []manifestStableEnumValue{
				enumValue("DegradationReasonV1MissingDiscovery", "missing-discovery"),
				enumValue("DegradationReasonV1DeniedTrust", "denied-trust"),
				enumValue("DegradationReasonV1RemoteDisconnect", "remote-disconnect"),
				enumValue("DegradationReasonV1CertificateUnavailable", "certificate-unavailable"),
				enumValue("DegradationReasonV1NoVisibleServices", "no-visible-services"),
				enumValue("DegradationReasonV1NoData", "no-data"),
			}},
			{exact: true, typeName: "ServiceKindV1", values: []manifestStableEnumValue{
				enumValue("ServiceKindV1Local", "local"),
				enumValue("ServiceKindV1Remote", "remote"),
			}},
			{exact: true, typeName: "ObservedSessionStateV1", values: []manifestStableEnumValue{
				enumValue("ObservedSessionStateV1Unknown", "unknown"),
				enumValue("ObservedSessionStateV1Connecting", "connecting"),
				enumValue("ObservedSessionStateV1Connected", "connected"),
				enumValue("ObservedSessionStateV1Disconnected", "disconnected"),
				enumValue("ObservedSessionStateV1Degraded", "degraded"),
			}},
			{exact: true, typeName: "FeatureRoleV1", values: []manifestStableEnumValue{
				enumValue("FeatureRoleV1Unspecified", ""),
				enumValue("FeatureRoleV1Client", "client"),
				enumValue("FeatureRoleV1Server", "server"),
			}},
		},
	}
}

func stableNativeSnapshotV2ContractSpec(modulePath, rawPath, evidencePath string, field stableContractFieldFactory, stableType stableContractTypeFactory, enumValue stableContractEnumFactory) stableContractSpec {
	return stableContractSpec{
		importPath: modulePath,
		optional:   true,
		root:       "NativeSnapshotV2",
		enums: []stableEnumSpec{
			{values: []manifestStableEnumValue{
				enumValue("NativeSnapshotContractV2", "helianthus.eebus.runtime.native-snapshot.v2"),
			}},
		},
	}
}

func stableIdentityDocumentV1ContractSpec(modulePath, rawPath, evidencePath string, field stableContractFieldFactory, stableType stableContractTypeFactory, enumValue stableContractEnumFactory) stableContractSpec {
	return stableContractSpec{
		importPath: rawPath,
		root:       "IdentityDocumentV1",
		types: []manifestStableType{
			stableType("ContractVersion", "string"),
			stableType("MaskTier", "string"),
			stableType("EndpointRoleV1", "string"),
			stableType("IDKind", "string"),
			stableType("RedactedID", "struct",
				field("Kind", "IDKind", `json:"kind"`),
				field("Masked", "string", `json:"masked"`),
				field("Digest", "string", `json:"digest,omitempty"`),
			),
			stableType("UnknownPath", "string"),
			stableType("UnknownField", "struct",
				field("Path", "UnknownPath", `json:"path"`),
				field("Value", "OpaqueValue", `json:"value"`),
			),
			stableType("OpaqueValue", "struct",
				field("Masked", "string", `json:"masked"`),
				field("Digest", "string", `json:"digest,omitempty"`),
				field("Size", "int", `json:"size,omitempty"`),
			),
			stableType("EndpointIdentityV1", "struct",
				field("Role", "EndpointRoleV1", `json:"role"`),
				field("ID", "RedactedID", `json:"id"`),
				field("Unknown", "[]UnknownField", `json:"unknown,omitempty"`),
			),
			stableType("SessionIdentityV1", "struct",
				field("ID", "RedactedID", `json:"id"`),
				field("RemoteID", "RedactedID", `json:"remote_id"`),
				field("Unknown", "[]UnknownField", `json:"unknown,omitempty"`),
			),
			stableType("IdentityDocumentV1", "struct",
				field("Contract", "ContractVersion", `json:"contract"`),
				field("MaskTier", "MaskTier", `json:"mask_tier"`),
				field("CapturedAt", "time.Time", `json:"captured_at"`),
				field("Local", "EndpointIdentityV1", `json:"local"`),
				field("Remotes", "[]EndpointIdentityV1", `json:"remotes,omitempty"`),
				field("Sessions", "[]SessionIdentityV1", `json:"sessions,omitempty"`),
				field("Unknown", "[]UnknownField", `json:"unknown,omitempty"`),
			),
		},
		enums: []stableEnumSpec{
			{typeName: "ContractVersion", values: []manifestStableEnumValue{enumValue("IdentityContractV1", "helianthus.eebus.raw.identity.v1")}},
			{typeName: "MaskTier", values: []manifestStableEnumValue{enumValue("MaskTierRedacted", "redacted")}},
			{exact: true, typeName: "EndpointRoleV1", values: []manifestStableEnumValue{
				enumValue("EndpointRoleV1Local", "local"),
				enumValue("EndpointRoleV1Remote", "remote"),
			}},
			{exact: true, typeName: "IDKind", values: []manifestStableEnumValue{
				enumValue("IDKindLocalSKI", "local-ski"),
				enumValue("IDKindRemoteSKI", "remote-ski"),
				enumValue("IDKindCertificateFingerprint", "certificate-fingerprint"),
				enumValue("IDKindPeer", "peer"),
				enumValue("IDKindSession", "session"),
			}},
			{exact: true, typeName: "UnknownPath", values: []manifestStableEnumValue{
				enumValue("UnknownPathDocument", "/document/unknown"),
				enumValue("UnknownPathDevice", "/device/unknown"),
				enumValue("UnknownPathLocal", "/local/unknown"),
				enumValue("UnknownPathRemote", "/remote/unknown"),
				enumValue("UnknownPathSession", "/session/unknown"),
			}},
		},
	}
}

func stableReadAuthorizationV1ContractSpec(modulePath, rawPath, evidencePath string, field stableContractFieldFactory, stableType stableContractTypeFactory, enumValue stableContractEnumFactory) stableContractSpec {
	return stableContractSpec{
		importPath: rawPath,
		root:       "ReadAuthorizationV1",
		types: []manifestStableType{
			stableType("ToolV1", "string"),
			stableType("AuthScopeV1", "string"),
			stableType("FeatureRoleV1", "string"),
			stableType("OperationV1", "string"),
			stableType("ObservationSourceV1", "string"),
			stableType("ChangeabilityV1", "string"),
			stableType("ConstraintStatusV1", "string"),
			stableType("ErrorCodeV1", "string"),
			stableType("SourceLayerV1", "string"),
			stableType("HashV1", "string"),
			stableType("TypedValueV1", "struct"),
			stableType("ReadAuthorizationV1", "struct",
				field("PrincipalClass", "string", `json:"principal_class"`),
				field("Scope", "AuthScopeV1", `json:"scope"`),
				field("Tool", "ToolV1", `json:"tool"`),
				field("MaskTier", "MaskTier", `json:"mask_tier"`),
			),
			stableType("WriteAuthorizationV1", "struct",
				field("PrincipalClass", "string", `json:"principal_class"`),
				field("Scope", "AuthScopeV1", `json:"scope"`),
				field("Tool", "ToolV1", `json:"tool"`),
				field("MaskTier", "MaskTier", `json:"mask_tier"`),
			),
			stableType("ModeV1", "string"),
			stableType("MutationStateV1", "string"),
			stableType("ConstraintOverrideV1", "struct",
				field("ProfileID", "string", `json:"profile_id"`),
				field("Justification", "string", `json:"justification"`),
				field("ExpiresAt", "time.Time", `json:"expires_at"`),
			),
			stableType("MutationLabProfileV1", "struct",
				field("Contract", "string", `json:"contract"`),
				field("ProfileID", "string", `json:"profile_id"`),
				field("Target", "FeatureTargetV1", `json:"target"`),
				field("AllowedValueHashes", "[]HashV1", `json:"allowed_value_hashes"`),
				field("RollbackValueHash", "HashV1", `json:"rollback_value_hash"`),
				field("MaximumProbeTTLSeconds", "uint64", `json:"maximum_probe_ttl_seconds"`),
				field("SafetyPredicates", "[]string", `json:"safety_predicates"`),
				field("EvidenceHashes", "[]HashV1", `json:"evidence_hashes"`),
				field("ExpiresAt", "time.Time", `json:"expires_at"`),
			),
			stableType("FeatureDataSetRequestV1", "struct",
				field("Target", "FeatureTargetV1", `json:"target"`),
				field("Value", "TypedValueV1", `json:"value"`),
				field("ReadToken", "string", `json:"read_token"`),
				field("ExpectedCurrent", "*TypedValueV1", `json:"expected_current,omitempty"`),
				field("IdempotencyKey", "string", `json:"idempotency_key"`),
				field("Mode", "ModeV1", `json:"mode"`),
				field("ProbeTTLSeconds", "uint64", `json:"probe_ttl_seconds,omitempty"`),
				field("ConstraintsOverride", "*ConstraintOverrideV1", `json:"constraints_override,omitempty"`),
			),
			stableType("MutationGetRequestV1", "struct",
				field("MutationRef", "string", `json:"mutation_ref"`),
			),
			stableType("MutationRollbackRequestV1", "struct",
				field("MutationRef", "string", `json:"mutation_ref"`),
				field("IdempotencyKey", "string", `json:"idempotency_key"`),
			),
			stableType("AuditTransitionV1", "struct",
				field("Sequence", "uint64", `json:"sequence"`),
				field("State", "MutationStateV1", `json:"state"`),
				field("TransitionedAt", "time.Time", `json:"transitioned_at"`),
				field("Classification", "string", `json:"classification,omitempty"`),
				field("PreviousHash", "*HashV1", `json:"previous_hash"`),
				field("TransitionHash", "HashV1", `json:"transition_hash"`),
			),
			stableType("ApplyVerificationV1", "struct",
				field("Relation", "string", `json:"relation"`),
				field("Verified", "bool", `json:"verified"`),
				field("EqualValueHash", "HashV1", `json:"equal_value_hash"`),
				field("VerifiedAt", "time.Time", `json:"verified_at"`),
			),
			stableType("RollbackVerificationV1", "struct",
				field("Relation", "string", `json:"relation"`),
				field("Verified", "bool", `json:"verified"`),
				field("EqualValueHash", "HashV1", `json:"equal_value_hash"`),
				field("VerifiedAt", "time.Time", `json:"verified_at"`),
			),
			stableType("ConflictEvidenceV1", "struct",
				field("Relation", "string", `json:"relation"`),
				field("Verified", "bool", `json:"verified"`),
				field("BeforeHash", "HashV1", `json:"before_hash"`),
				field("RequestedHash", "HashV1", `json:"requested_hash"`),
				field("ObservedAfterHash", "HashV1", `json:"observed_after_hash"`),
				field("VerifiedAt", "time.Time", `json:"verified_at"`),
			),
			stableType("NoContactEvidenceV1", "struct",
				field("RemoteFramesSent", "uint64", `json:"remote_frames_sent"`),
				field("LastCompletedPhase", "string", `json:"last_completed_phase"`),
				field("VerifiedAt", "time.Time", `json:"verified_at"`),
			),
			stableType("RejectionVerificationV1", "struct",
				field("Relation", "string", `json:"relation"`),
				field("Verified", "bool", `json:"verified"`),
				field("CorrelatedRejection", "bool", `json:"correlated_rejection"`),
				field("EqualValueHash", "HashV1", `json:"equal_value_hash"`),
				field("VerifiedAt", "time.Time", `json:"verified_at"`),
			),
			stableType("NoEffectVerificationV1", "struct",
				field("Relation", "string", `json:"relation"`),
				field("Verified", "bool", `json:"verified"`),
				field("EqualValueHash", "HashV1", `json:"equal_value_hash"`),
				field("VerifiedAt", "time.Time", `json:"verified_at"`),
			),
			stableType("OutcomeEvidenceV1", "struct",
				field("PossibleSideEffect", "bool", `json:"possible_side_effect"`),
				field("BlindRetryForbidden", "bool", `json:"blind_retry_forbidden"`),
				field("LastDurableState", "MutationStateV1", `json:"last_durable_state"`),
				field("RecordedAt", "time.Time", `json:"recorded_at"`),
			),
			stableType("RollbackV1", "struct",
				field("State", "MutationStateV1", `json:"state"`),
				field("Before", "TypedValueV1", `json:"before"`),
				field("ProtocolAccepted", "*bool", `json:"protocol_accepted"`),
				field("ObservedAfter", "*TypedValueV1", `json:"observed_after"`),
				field("Error", "*ErrorV1", `json:"error,omitempty"`),
				field("Verification", "*RollbackVerificationV1", `json:"verification,omitempty"`),
			),
			stableType("MutationV1", "struct",
				field("MutationRef", "string", `json:"mutation_ref"`),
				field("State", "MutationStateV1", `json:"state"`),
				field("Mode", "ModeV1", `json:"mode"`),
				field("Target", "FeatureTargetV1", `json:"target"`),
				field("Runtime", "RuntimeBindingV1", `json:"runtime"`),
				field("Before", "TypedValueV1", `json:"before"`),
				field("Requested", "TypedValueV1", `json:"requested"`),
				field("ProtocolAccepted", "*bool", `json:"protocol_accepted"`),
				field("ObservedAfter", "*TypedValueV1", `json:"observed_after"`),
				field("Rollback", "*RollbackV1", `json:"rollback,omitempty"`),
				field("ProbeDeadline", "*time.Time", `json:"probe_deadline,omitempty"`),
				field("CreatedAt", "time.Time", `json:"created_at"`),
				field("UpdatedAt", "time.Time", `json:"updated_at"`),
				field("Error", "*ErrorV1", `json:"error,omitempty"`),
				field("ApplyVerification", "*ApplyVerificationV1", `json:"apply_verification,omitempty"`),
				field("ConflictEvidence", "*ConflictEvidenceV1", `json:"conflict_evidence,omitempty"`),
				field("NoContactEvidence", "*NoContactEvidenceV1", `json:"no_contact_evidence,omitempty"`),
				field("RejectionVerification", "*RejectionVerificationV1", `json:"rejection_verification,omitempty"`),
				field("NoEffectVerification", "*NoEffectVerificationV1", `json:"no_effect_verification,omitempty"`),
				field("OutcomeEvidence", "*OutcomeEvidenceV1", `json:"outcome_evidence,omitempty"`),
				field("Audit", "[]AuditTransitionV1", `json:"audit"`),
			),
			stableType("RuntimeBindingV1", "struct",
				field("RuntimeEpoch", "uint64", `json:"runtime_epoch"`),
				field("ConnectionGeneration", "uint64", `json:"connection_generation"`),
			),
			stableType("FeatureLocatorV1", "struct",
				field("RemoteSKI", "string", `json:"remote_ski"`),
				field("SHIPID", "string", `json:"ship_id"`),
				field("DeviceAddress", "string", `json:"device_address"`),
				field("EntityAddress", "[]uint64", `json:"entity_address"`),
				field("FeatureAddress", "uint64", `json:"feature_address"`),
				field("FeatureType", "string", `json:"feature_type"`),
				field("FeatureRole", "FeatureRoleV1", `json:"feature_role"`),
			),
			stableType("FeatureTargetV1", "struct",
				field("RemoteSKI", "string", `json:"remote_ski"`),
				field("SHIPID", "string", `json:"ship_id"`),
				field("DeviceAddress", "string", `json:"device_address"`),
				field("EntityAddress", "[]uint64", `json:"entity_address"`),
				field("FeatureAddress", "uint64", `json:"feature_address"`),
				field("FeatureType", "string", `json:"feature_type"`),
				field("FeatureRole", "FeatureRoleV1", `json:"feature_role"`),
				field("Function", "string", `json:"function"`),
				field("Operation", "OperationV1", `json:"operation"`),
			),
			stableType("FullOperationsV1", "struct",
				field("Read", "bool", `json:"read"`),
				field("Write", "bool", `json:"write"`),
			),
			stableType("ConstraintSetV1", "struct",
				field("Status", "ConstraintStatusV1", `json:"status"`),
				field("EnumValues", "[]TypedValueV1", `json:"enum_values,omitempty"`),
				field("Minimum", "*TypedValueV1", `json:"minimum,omitempty"`),
				field("Maximum", "*TypedValueV1", `json:"maximum,omitempty"`),
				field("Step", "*TypedValueV1", `json:"step,omitempty"`),
				field("Unit", "string", `json:"unit,omitempty"`),
				field("MinCardinality", "*uint64", `json:"min_cardinality,omitempty"`),
				field("MaxCardinality", "*uint64", `json:"max_cardinality,omitempty"`),
				field("CrossFieldRules", "[]string", `json:"cross_field_rules,omitempty"`),
			),
			stableType("FunctionDescriptorV1", "struct",
				field("Function", "string", `json:"function"`),
				field("Description", "string", `json:"description,omitempty"`),
				field("PossibleOperations", "FullOperationsV1", `json:"possible_operations"`),
				field("Changeable", "ChangeabilityV1", `json:"changeable"`),
				field("Constraints", "ConstraintSetV1", `json:"constraints"`),
			),
			stableType("FeaturesGetRequestV1", "struct",
				field("Target", "FeatureLocatorV1", `json:"target"`),
			),
			stableType("FeaturesGetDataV1", "struct",
				field("Feature", "FeatureLocatorV1", `json:"feature"`),
				field("Description", "string", `json:"description,omitempty"`),
				field("Functions", "[]FunctionDescriptorV1", `json:"functions"`),
				field("Runtime", "RuntimeBindingV1", `json:"runtime"`),
				field("DataTimestamp", "time.Time", `json:"data_timestamp"`),
				field("Source", "ObservationSourceV1", `json:"source"`),
				field("DataHash", "HashV1", `json:"data_hash"`),
			),
			stableType("FeatureDataGetRequestV1", "struct",
				field("Targets", "[]FeatureTargetV1", `json:"targets"`),
				field("TimeoutMS", "uint64", `json:"timeout_ms,omitempty"`),
			),
			stableType("ProtocolMessageV1", "struct",
				field("Classifier", "string", `json:"classifier"`),
				field("CorrelationKey", "uint64", `json:"correlation_key"`),
				field("Function", "string", `json:"function"`),
				field("Data", "*TypedValueV1", `json:"data,omitempty"`),
				field("ErrorNumber", "*uint64", `json:"error_number,omitempty"`),
				field("Unknown", "[]OpaqueObservationV1", `json:"unknown,omitempty"`),
			),
			stableType("OpaqueObservationV1", "struct",
				field("Path", "string", `json:"path"`),
				field("Source", "string", `json:"source"`),
				field("Value", "TypedValueV1", `json:"value"`),
			),
			stableType("ReadTokenV1", "struct",
				field("ReadToken", "string", `json:"read_token"`),
				field("Reusable", "bool", `json:"reusable"`),
				field("ExpiresAt", "time.Time", `json:"expires_at"`),
				field("BindingHash", "HashV1", `json:"binding_hash"`),
			),
			stableType("ReadObservationV1", "struct",
				field("Target", "FeatureTargetV1", `json:"target"`),
				field("Runtime", "RuntimeBindingV1", `json:"runtime"`),
				field("RawRequest", "ProtocolMessageV1", `json:"raw_request"`),
				field("RawResponse", "ProtocolMessageV1", `json:"raw_response"`),
				field("Value", "TypedValueV1", `json:"value"`),
				field("Unknown", "[]OpaqueObservationV1", `json:"unknown,omitempty"`),
				field("RequestedAt", "time.Time", `json:"requested_at"`),
				field("ReceivedAt", "time.Time", `json:"received_at"`),
				field("DataTimestamp", "time.Time", `json:"data_timestamp"`),
				field("Source", "ObservationSourceV1", `json:"source"`),
				field("ReadToken", "ReadTokenV1", `json:"read_token"`),
				field("DataHash", "HashV1", `json:"data_hash"`),
			),
			stableType("ErrorV1", "struct",
				field("Code", "ErrorCodeV1", `json:"code"`),
				field("Message", "string", `json:"message"`),
				field("Retriable", "bool", `json:"retriable"`),
				field("SourceLayer", "SourceLayerV1", `json:"source_layer"`),
				field("Details", "*ErrorDetailsV1", `json:"details,omitempty"`),
			),
			stableType("ErrorDetailsV1", "struct",
				field("TargetIndex", "*uint64", `json:"target_index,omitempty"`),
				field("Classification", "string", `json:"classification,omitempty"`),
				field("Unknown", "[]OpaqueObservationV1", `json:"unknown,omitempty"`),
			),
			stableType("ReadFailureV1", "struct",
				field("TargetIndex", "uint64", `json:"target_index"`),
				field("Target", "FeatureTargetV1", `json:"target"`),
				field("Error", "ErrorV1", `json:"error"`),
			),
			stableType("FeatureDataGetDataV1", "struct",
				field("Results", "[]ReadObservationV1", `json:"results"`),
				field("Failures", "[]ReadFailureV1", `json:"failures"`),
				field("Complete", "bool", `json:"complete"`),
			),
		},
		enums: []stableEnumSpec{
			{exact: true, typeName: "ToolV1", values: []manifestStableEnumValue{
				enumValue("ToolV1FeaturesGet", "eebus.v1.features.get"),
				enumValue("ToolV1FeaturesDataGet", "eebus.v1.features.data.get"),
				enumValue("ToolV1FeaturesDataSet", "eebus.v1.features.data.set"),
				enumValue("ToolV1MutationsGet", "eebus.v1.mutations.get"),
				enumValue("ToolV1MutationsRollback", "eebus.v1.mutations.rollback"),
			}},
			{exact: true, typeName: "AuthScopeV1", values: []manifestStableEnumValue{
				enumValue("AuthScopeV1RawRead", "eebus.raw.read"),
				enumValue("AuthScopeV1RawWrite", "eebus.raw.write"),
			}},
			{exact: true, typeName: "ModeV1", values: []manifestStableEnumValue{
				enumValue("ModeV1Apply", "apply"),
				enumValue("ModeV1Probe", "probe"),
			}},
			{exact: true, typeName: "MutationStateV1", values: []manifestStableEnumValue{
				enumValue("MutationStateV1Prepared", "prepared"),
				enumValue("MutationStateV1DispatchIntent", "dispatch_intent"),
				enumValue("MutationStateV1ReplyObserved", "reply_observed"),
				enumValue("MutationStateV1VerifyPending", "verify_pending"),
				enumValue("MutationStateV1Applied", "applied"),
				enumValue("MutationStateV1ProbeActive", "probe_active"),
				enumValue("MutationStateV1RollbackIntent", "rollback_intent"),
				enumValue("MutationStateV1RollbackDispatchIntent", "rollback_dispatch_intent"),
				enumValue("MutationStateV1RollbackReplyObserved", "rollback_reply_observed"),
				enumValue("MutationStateV1RollbackVerifyPending", "rollback_verify_pending"),
				enumValue("MutationStateV1RolledBack", "rolled_back"),
				enumValue("MutationStateV1OutcomeUnknown", "outcome_unknown"),
				enumValue("MutationStateV1Conflict", "conflict"),
				enumValue("MutationStateV1FailedNoContact", "failed_no_contact"),
				enumValue("MutationStateV1Rejected", "rejected"),
				enumValue("MutationStateV1NoEffect", "no_effect"),
			}},
			{exact: true, typeName: "FeatureRoleV1", values: []manifestStableEnumValue{
				enumValue("FeatureRoleV1Client", "client"),
				enumValue("FeatureRoleV1Server", "server"),
				enumValue("FeatureRoleV1Special", "special"),
			}},
			{exact: true, typeName: "OperationV1", values: []manifestStableEnumValue{
				enumValue("OperationV1Read", "READ"),
				enumValue("OperationV1Write", "WRITE"),
			}},
			{exact: true, typeName: "ObservationSourceV1", values: []manifestStableEnumValue{
				enumValue("ObservationSourceV1Live", "live"),
				enumValue("ObservationSourceV1Cache", "cache"),
			}},
			{exact: true, typeName: "ChangeabilityV1", values: []manifestStableEnumValue{
				enumValue("ChangeabilityV1Unknown", "unknown"),
				enumValue("ChangeabilityV1False", "false"),
				enumValue("ChangeabilityV1True", "true"),
			}},
			{exact: true, typeName: "ConstraintStatusV1", values: []manifestStableEnumValue{
				enumValue("ConstraintStatusV1Unknown", "unknown"),
				enumValue("ConstraintStatusV1Known", "known"),
			}},
			{exact: true, typeName: "ErrorCodeV1", values: []manifestStableEnumValue{
				enumValue("ErrorCodeV1PermissionDenied", "permission_denied"),
				enumValue("ErrorCodeV1InvalidArgument", "invalid_argument"),
				enumValue("ErrorCodeV1UnsupportedOperation", "unsupported_operation"),
				enumValue("ErrorCodeV1PartialOperationForbidden", "partial_operation_forbidden"),
				enumValue("ErrorCodeV1ConstraintsUnknown", "constraints_unknown"),
				enumValue("ErrorCodeV1ConstraintFailure", "constraint_failure"),
				enumValue("ErrorCodeV1StaleReadToken", "stale_read_token"),
				enumValue("ErrorCodeV1CASMismatch", "cas_mismatch"),
				enumValue("ErrorCodeV1RuntimeEpochMismatch", "runtime_epoch_mismatch"),
				enumValue("ErrorCodeV1ConnectionGenerationMismatch", "connection_generation_mismatch"),
				enumValue("ErrorCodeV1IdempotencyConflict", "idempotency_conflict"),
				enumValue("ErrorCodeV1WriterBusy", "writer_busy"),
				enumValue("ErrorCodeV1Disconnected", "disconnected"),
				enumValue("ErrorCodeV1Timeout", "timeout"),
				enumValue("ErrorCodeV1Cancelled", "cancelled"),
				enumValue("ErrorCodeV1RemoteError", "remote_error"),
				enumValue("ErrorCodeV1TypedEmpty", "typed_empty"),
				enumValue("ErrorCodeV1DecodeError", "decode_error"),
				enumValue("ErrorCodeV1PartialResult", "partial_result"),
				enumValue("ErrorCodeV1OutcomeUnknown", "outcome_unknown"),
				enumValue("ErrorCodeV1Conflict", "conflict"),
				enumValue("ErrorCodeV1RollbackFailed", "rollback_failed"),
				enumValue("ErrorCodeV1NoEffect", "no_effect"),
				enumValue("ErrorCodeV1NotFound", "not_found"),
				enumValue("ErrorCodeV1SecretDetected", "secret_detected"),
				enumValue("ErrorCodeV1Internal", "internal"),
			}},
			{exact: true, typeName: "SourceLayerV1", values: []manifestStableEnumValue{
				enumValue("SourceLayerV1Authorization", "eebusreg-runtime"),
				enumValue("SourceLayerV1Validation", "eebusreg-runtime"),
				enumValue("SourceLayerV1Runtime", "eebusreg-runtime"),
				enumValue("SourceLayerV1Executor", "eebus-go-executor"),
				enumValue("SourceLayerV1SpineRoundTrip", "spine-go-round-trip"),
				enumValue("SourceLayerV1Decode", "eebusreg-runtime"),
				enumValue("SourceLayerV1Remote", "remote"),
			}},
		},
	}
}

func stableEnvelopeV1ContractSpec(modulePath, rawPath, evidencePath string, field stableContractFieldFactory, stableType stableContractTypeFactory, enumValue stableContractEnumFactory) stableContractSpec {
	return stableContractSpec{
		importPath: evidencePath,
		root:       "EnvelopeV1",
		types: []manifestStableType{
			stableType("ContractVersion", "string"),
			stableType("CaptureProvenanceV1", "string"),
			stableType("RawSnapshotScopeV1", "string"),
			stableType("AuthScope", "string"),
			stableType("ObjectKind", "string"),
			stableType("ReferenceV1", "struct",
				field("Runtime", rawPath+".RedactedID", `json:"runtime"`),
				field("Contract", "ContractVersion", `json:"contract"`),
				field("CaptureProvenance", "CaptureProvenanceV1", `json:"capture_provenance"`),
				field("Scope", "RawSnapshotScopeV1", `json:"scope"`),
				field("MaskTier", rawPath+".MaskTier", `json:"mask_tier"`),
				field("AuthScope", "AuthScope", `json:"auth_scope"`),
			),
			stableType("ObjectV1", "struct",
				field("Kind", "ObjectKind", `json:"kind"`),
				field("Digest", "string", `json:"digest"`),
				field("Size", "int", `json:"size"`),
				field("DataTimestamp", "time.Time", `json:"data_timestamp"`),
				field("Unknown", "[]"+rawPath+".UnknownField", `json:"unknown,omitempty"`),
			),
			stableType("EnvelopeV1", "struct",
				field("Reference", "ReferenceV1", `json:"ref"`),
				field("CapturedAt", "time.Time", `json:"captured_at"`),
				field("DataTimestamp", "time.Time", `json:"data_timestamp"`),
				field("Objects", "[]ObjectV1", `json:"objects,omitempty"`),
				field("DataHash", "string", `json:"data_hash,omitempty"`),
			),
		},
		enums: []stableEnumSpec{
			{typeName: "ContractVersion", values: []manifestStableEnumValue{enumValue("EnvelopeContractV1", "helianthus.eebus.raw.evidence-envelope.v1")}},
			{exact: true, typeName: "CaptureProvenanceV1", values: []manifestStableEnumValue{
				enumValue("CaptureProvenanceRuntimeObservation", "runtime-observation"),
			}},
			{exact: true, typeName: "RawSnapshotScopeV1", values: []manifestStableEnumValue{
				enumValue("RawSnapshotScopeRoot", "raw-root"),
				enumValue("RawSnapshotScopeIdentity", "raw-identity"),
				enumValue("RawSnapshotScopeTopology", "raw-topology"),
				enumValue("RawSnapshotScopeServices", "raw-services"),
				enumValue("RawSnapshotScopeSessions", "raw-sessions"),
				enumValue("RawSnapshotScopeUnknown", "raw-unknown"),
			}},
			{exact: true, typeName: "AuthScope", values: []manifestStableEnumValue{enumValue("AuthScopeReadRaw", "eebus.raw.read")}},
			{exact: true, typeName: "ObjectKind", values: []manifestStableEnumValue{
				enumValue("ObjectKindIdentity", "identity"),
				enumValue("ObjectKindTopology", "topology"),
				enumValue("ObjectKindService", "service"),
				enumValue("ObjectKindSession", "session"),
				enumValue("ObjectKindUnknown", "unknown"),
			}},
		},
	}
}
